<?php
/**
 * @var \Boolfly\Blog\Block\Widget\BlogPost $block
 */
$format = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$posts = $block->getPostList();
?>
<?php if ($posts->count()): ?>
    <div class="widget-post-grid">
        <div class="content-heading">
            <h2 class="title"><?= $block->escapeHtml($block->getContentHeading()); ?></h2>
            <p class="info"><?= $block->escapeHtml($block->getContentDescription()); ?></p>
        </div>
        <div class="block-content">
            <div class="post-items-widget-post-grid post-items">
                <?php foreach ($posts as $post): ?>
                    <div class="post-item blog-post-list-item">
                        <a href="<?= $block->escapeUrl($post->getPostUrl()) ?>" class="post-link">
                            <div class="blog-post-item-image">
                                <img class="post-image" src="<?= $post->getImageUrl(); ?>"
                                     alt="<?= $block->escapeHtml($post->getTitle()) ?>"/>
                            </div>
                        </a>
                        <h3 class="blog-post-item-title">
                            <a href="<?= $block->escapeUrl($post->getPostUrl()) ?>" class="post-item-link">
                                <?= $block->escapeHtml(__($post->getTitle())) ?>
                            </a>
                        </h3>
                        <div class="blog-post-item-short-content"><?= $block->escapeHtml($post->getShortContent()) ?></div>
                        <div class="blog-post-item-meta">
                            <?php echo __('Author: '); ?>
                            <a class="author-link" href="<?= $block->escapeUrl($post->getAuthorUrl()) ?>">
                                <span class="author-name"><?= $block->escapeHtml($post->getAuthorFullName()) ?></span>
                            </a>
                            <?= $block->escapeHtml($block->formatDate($post->getCreationTime(), $format)) ?>
                        </div>
                        <div class="read-more">
                            <a href="<?= $block->escapeUrl($post->getPostUrl()) ?>" class="post-link">
                                <?= $block->escapeHtml(__('Read more')) ?>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>